blank_issues_enabled: true
contact_links:
  - name: ðŸ“– Contributing Guidelines
    url: https://github.com/zeroae/.github/blob/main/.github/CONTRIBUTING.md
    about: Please read before opening an issue
